language: R
sudo: false
cache: packages

matrix:
  include:
  - r: devel
  - r: release
    r_github_packages:
    - jimhester/lintr
    - r-lib/pkgdown
    - r-lib/covr
    after_success:
    - R CMD INSTALL $PKG_TARBALL
    - Rscript -e 'covr::codecov()'
    - Rscript -e 'lintr::lint_package()'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
